version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iruka_quiz_pod
      POSTGRES_PASSWORD: "6ddXvhO1E62v-GnDsKnfWYR_7CjWyPdv"
    volumes:
      - iruka_quiz_pod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "zeKEbTMzmINl3whzMkV_2xcsm0v1s-vf"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  iruka_quiz_pod_data:
